version: '3.9'
services:
  app:
    container_name: todo
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    env_file:
      - .env
    build: .
    links:
      - redis
      - db
    ports:
      - "9090:9090"
  redis:
    container_name: redis
    command: redis-server --requirepass password
    build: ./redis
    ports:
      - "6379:6379"
  db:
    container_name: postgres
    image: postgres
    restart: always
    ports:
        - "5432:5432"
    environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
